name: WarpPlugin
main: therr.WarpPlugin.WarpPlugin
version: 1.4
author: Mateusz Buchajewicz
commands:
  setwarp:
    description: Sets warp with given name in place where you are.
    usage: /setwarp [warp_name]
    permission: WarpPlugin.setwarp
    permissoin-message: You don't have permission to use setwarp!
  warp:
    description: Teleports you to warp with given name.
    usage: /warp [warp_name]
    permission: WarpPlugin.warp
    permissoin-message: You don't have permission to use warp!
  delwarp:
    description: Deletes warp with given name
    usage: /delwarp [warp_name]
    permission: WarpPlugin.delwarp
    permissoin-message: You don't have permission to use delwarp!
  warplist:
    description: Shows list of current warps
    usage: /warplist
    permission: WarpPlugin.warplist
    permissoin-message: You don't have permission to use warplist!
  warprename:
    description: Renames warp
    usage: /warprename [warp_to_rename] [new_name]
    permission: WarpPlugin.warprename
    permission-message: You don't have permission to use warprename!
  warpupdate:
    description: Updates existing's warp location to current player location.
    usage: /warpupdate [warp_to_update]
    permission: WarpPlugin.warpupdate
    permission-message: You don't have permission to use warpUpdate!
  warpshare:
    description: Shares warp with other player
    usage: /warpshare [player_name] [warp_name]
    permission-message: You don't have permission to use warpshare!
    permission: WarpPlugin.warpshare