name: WarpPlugin
main: therr.WarpPlugin.WarpPlugin
version: 1.0
author: Mateusz Buchajewicz
commands:
  warp:
    description: Warp info command
    usage: /warp <command> [warp name]
    permission: WarpPlugin.warp
    permissoin-message: You don't have permission to use warp!